---
name: Config-Any-Merge
version: 0.07
author:
  - 'Mario Domgoergen, C< <dom@math.uni-bonn.de> >'
abstract: Overrinding of configuration variables based on file order
license: perl
resources:
  license: ~
requires:
  Config::Any: 0.15
  Hash::Merge: 0
build_requires:
  Config::Tiny: 0
  Test::More: 0
provides:
  Config::Any::Merge:
    file: lib/Config/Any/Merge.pm
    version: 0.07
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
