---
name: Config-Any-Merge
version: 0.06
author: []
abstract: Overrinding of configuration variables based on file order
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Config::Any: 0.15
  Hash::Merge: 0
build_requires:
  Config::Tiny: 0
  Test::More: 0
provides:
  Config::Any::Merge:
    file: lib/Config/Any/Merge.pm
    version: 0.06
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
